spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33081/caffe-map-test-db
    username: user
    password: password
    hikari:
      maximum-pool-size: 40
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE